version: '3'
services:
  mongo:
    image: 'mongo'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./dashboard-server
    volumes:
      - /app/node_modules
      - ./dashboard-server:/app
    environment:
      - SECRET_KEY=fmdskgn3934et09532jmnfb8c9vcc
      - MONGO_HOST=mongodb://mongo:27017/dashboard
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./dashboard-client
    volumes:
      - /app/node_modules
      - ./dashboard-client:/app